---
language: python
env:
  global:
  - secure: 'lSo8davuNDmkcgbj6TRFETR7TCbdQjpl369OtFCAsFaX2W+z3OSmdJHYvA1aXvaB4CLcXhaYNLt4UnmaYlfjaZe2ahnVKGUGUi1h0DpruYULL2Imq2/86b3GWboje4d9l5SwUiFnFLb4J4ZYFV/pbsmaNR0bGGFuQMHiHFWTmfN15C8zFK7PguVTIbaSC3mYjdhS8xjnj2ITnegfnOLYaDAq04FkjaixVFIURCE5d4o7XnsGD55VJUtpln4f1e8lKepMyudBokc8VZtmYqSRmka44lo2jWw2YQqLqEK/c/UPlrT6rLu3vT2ZjP/i9blBS2RjKtA+CfvK4ErmZ0lJbInu59Ur0JN7/pzkU7baMKeqRp25cPlLq9glw+iYVd1n8+RopLScOiNjgOP3IhEtOPkIPjb7pxpLtw4GfeuNNJrg7qLyLnFAxGbi498eoRd6uhkRiP80byVW5ayOxxX5kJS8cVWJ0FwW2Uvbx0PNgjkc3lYDxuMZk+UpVOZ5HwnHepq8yKvFgnnpnRVc3tvckhkT3AW9m5SIMi/f479Z71cB5hqcLRPqwunDKtNPm5DCK8apyoFU1sGEFAL2kZmTQZmXRYAur1A5izfGVvx+rI4o7v/CINMh1D2w3s9HfDF9Of8jzT4iAyA8HZtY6i/by9vu5EuuMrf0CE7fgVngtyk=' # AWS_ACCESS_KEY_ID="xyz"
  - secure: 'ikc2c/1xKj0pvUV8/3jypepeCMf6PB3GWo1wJ4M0c+PvQXBIFH1nY7R3Zo7tLwiT0LUbnESS8Cr/ZDdPVgtg1NkvG9oIPfzl3GZc1UYDJg0rW08HN5akxOWUEHWlYUyEqOlIPj6rmVe2sgJHavHawzSR6xN/gutpraG65UhEJ/bxZxaP/XtYDzlTCRY0qr64qUcAKVt6oD/6f3n6qyotAhVjJZ1hg6j6acWPBWi2GYCh4L9iHOdustn1+GWb6NUUqXbdHP3oLbn58JvuTTFsSDolTGYJ2ML53LiiUTKs3BujUoDi8LBYYOr7Vym95Jiu4BZrGQDXQm1PRoNeZgqAE40K43pN0qJ2wseIyjsBpVPuP32jwoF5lrLBL3Qz9mE5PTWTXH9lMHCxUv9mlp48vjGLcr8CdfN3ZX580j0ihj5y4V1OvHY584sI2cR/TKCjAAYyUD5IYZVfkZNiB1DxfKiwiqR1szxXnhau4Z7RS8LRJM8QYjgNOIYyxO5i899TpW6GfjxeEeaGpqnZ1reGFeWdvM9Or8cX+uKPXQmaEDBpt5d0CLaD/x6mcjsfnvmfN8gLAh76Sa/burOV8nzKLL5K64pIiobB7ZtAHeIUNGZsi+G39OwaNm20F8UZSiX4hELoUecNVE3AeTn+K6AS7kN3ARlYA6XOM7NB7NcKzPA=' # AWS_SECRET_ACCESS_KEY="xyz"
  - 'AWS_DEFAULT_REGION=eu-west-1'
python:
- '2.7'
install:
- 'pip install yamllint==1.13.0'
- 'pip install awscli==1.16.69'
- 'pip install cfn-lint==0.10.1'
script:
- 'yamllint .'
- 'find . -type f \( -name ''*.yml'' -o -name ''*.yaml'' \) -a ! -name ''.*'' | while read file; do set -ex && cfn-lint --template "$file"; done;'
- 'find . -type f \( -name ''*.yml'' -o -name ''*.yaml'' \) -a ! -name ''.*'' | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then find . -type f \( -name ''*.yml'' -o -name ''*.yaml'' \) -a ! -name ''.*'' | while read file; do set -ex && aws cloudformation validate-template --template-body "file://$file" > /dev/null; done; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then aws s3 sync . s3://monitoring-jump-start --exclude ''*'' --include ''*.yml''; fi'
